;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_Text_Position
	.export		_TEXT
	.export		_Text_dim
	.export		_PALETTE
	.export		_Load_Text
	.export		_All_Off
	.export		_All_On
	.export		_Reset_Scroll
	.export		_Load_Palette
	.export		_main

.segment	"DATA"

_Text_dim:
	.byte	$0B

.segment	"RODATA"

_TEXT:
	.byte	$48,$6F,$6C,$61,$20,$6D,$75,$6E,$64,$6F,$21,$00
_PALETTE:
	.byte	$0F
	.byte	$17
	.byte	$28
	.byte	$39

.segment	"BSS"

_NMI_flag:
	.res	1,$00
_Frame_Count:
	.res	1,$00
_index:
	.res	1,$00
_Text_Position:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ Load_Text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Text: near

.segment	"CODE"

;
; if (Text_Position < Text_dim){
;
	ldx     #$00
	lda     _Text_Position
	cmp     _Text_dim
	txa
	bcs     L0073
;
; PPU_ADDRESS = 0x20;
;
	lda     #$20
	sta     $2006
;
; PPU_ADDRESS = 0xca + Text_Position; 
;
	lda     _Text_Position
	clc
	adc     #$CA
	sta     $2006
;
; PPU_DATA = TEXT[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT,y
	sta     $2007
;
; ++Text_Position;  
;
	inc     _Text_Position
;
; else {
;
	rts
;
; Text_Position = 0;
;
L0073:	sta     _Text_Position
;
; PPU_ADDRESS = 0x20;
;
	lda     #$20
	sta     $2006
;
; PPU_ADDRESS = 0xca;
;
	lda     #$CA
	sta     $2006
;
; for ( index = 0; index < Text_dim; ++index ){
;
	stx     _index
L0072:	lda     _index
	cmp     _Text_dim
	txa
	sbc     #$00
	bcs     L0037
;
; PPU_DATA = 32;  //  borra el texto con el tile #32 
;
	lda     #$20
	sta     $2007
;
; for ( index = 0; index < Text_dim; ++index ){
;
	inc     _index
	jmp     L0072
;
; }
;
L0037:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0; 
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; //  screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; 
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Reset_Scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Reset_Scroll: near

.segment	"CODE"

;
; PPU_ADDRESS = 0;
;
	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L0074:	lda     _index
	cmp     #$04
	bcs     L0064
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L0074
;
; }
;
L0064:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; All_On();
;
	jsr     _All_On
;
; while (NMI_flag == 0);  //  esperar hasta NMI
;
L0075:	lda     _NMI_flag
	beq     L0075
;
; NMI_flag = 0;
;
	lda     #$00
	sta     _NMI_flag
;
; if (Frame_Count == 10){ //  espera 30 frames = 0.5 seconds
;
	lda     _Frame_Count
	cmp     #$0A
	bne     L0075
;
; Load_Text();
;
	jsr     _Load_Text
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; Frame_Count = 0;
;
	lda     #$00
	sta     _Frame_Count
;
; while (1){ //  loop infinito
;
	jmp     L0075

.endproc

