;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_Text_Position
	.export		_test
	.export		_nPalette
	.export		_state
	.export		_TEXT
	.export		_TEXT2
	.export		_Text_dim
	.export		_PALETTE
	.export		_Attrib_Table
	.export		_All_Off
	.export		_All_On
	.export		_Load_Palette
	.export		_Reset_Scroll
	.export		_Load_Text
	.export		_Change_Atrib_table
	.export		_main

.segment	"DATA"

_Text_dim:
	.byte	$10

.segment	"RODATA"

_TEXT:
	.byte	$30,$30,$31,$31,$30,$30,$31,$31,$30,$30,$31,$31,$30,$30,$31,$31
	.byte	$00
_TEXT2:
	.byte	$32,$32,$33,$33,$32,$32,$33,$33,$32,$32,$33,$33,$32,$32,$33,$33
	.byte	$00
_PALETTE:
	.byte	$11
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$16
	.byte	$00
	.byte	$16
	.byte	$00
	.byte	$27
	.byte	$00
	.byte	$27
	.byte	$00
	.byte	$1A
	.byte	$00
	.byte	$1A
_Attrib_Table:
	.byte	$E4
	.byte	$72
	.byte	$1B
	.byte	$8D

.segment	"BSS"

.segment	"ZEROPAGE"
_NMI_flag:
	.res	1,$00
_Frame_Count:
	.res	1,$00
_index:
	.res	1,$00
_Text_Position:
	.res	1,$00
.segment	"BSS"
_test:
	.res	1,$00
_nPalette:
	.res	1,$00
_state:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0; 
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; // screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; 
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L011C:	lda     _index
	cmp     #$10
	bcs     L011D
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L011C
;
; PPU_ADDRESS = 0x23;
;
L011D:	lda     #$23
	sta     $2006
;
; PPU_ADDRESS = 0xda;
;
	lda     #$DA
	sta     $2006
;
; for( index = 0; index < sizeof(Attrib_Table); ++index ){
;
	lda     #$00
	sta     _index
L011E:	lda     _index
	cmp     #$04
	bcs     L0045
;
; PPU_DATA = Attrib_Table[index];
;
	ldy     _index
	lda     _Attrib_Table,y
	sta     $2007
;
; for( index = 0; index < sizeof(Attrib_Table); ++index ){
;
	inc     _index
	jmp     L011E
;
; }
;
L0045:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Reset_Scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Reset_Scroll: near

.segment	"CODE"

;
; PPU_ADDRESS = 0;
;
	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Text: near

.segment	"CODE"

;
; if (Text_Position < sizeof(TEXT)){
;
	lda     _Text_Position
	cmp     #$11
	bcs     L011F
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x88 + Text_Position; // one line down = add 0x20 to the low bit
;
	lda     _Text_Position
	clc
	adc     #$88
	sta     $2006
;
; PPU_DATA = TEXT[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT,y
	sta     $2007
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xa8 + Text_Position; // one line down = add 0x20 to the low bit
;
	lda     _Text_Position
	clc
	adc     #$A8
	sta     $2006
;
; PPU_DATA = TEXT[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT,y
	sta     $2007
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xc8 + Text_Position; // about the middle of the screen 21d0
;
	lda     _Text_Position
	clc
	adc     #$C8
	sta     $2006
;
; PPU_DATA = TEXT2[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT2,y
	sta     $2007
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xe8 + Text_Position; // one line down = add 0x20 to the low bit
;
	lda     _Text_Position
	clc
	adc     #$E8
	sta     $2006
;
; PPU_DATA = TEXT2[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT2,y
	sta     $2007
;
; ++Text_Position; 
;
	inc     _Text_Position
;
; else {
;
	rts
;
; Text_Position = 0;
;
L011F:	lda     #$00
	sta     _Text_Position
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x88; // one line down = add 0x20 to the low bit
;
	lda     #$88
	sta     $2006
;
; for ( index = 0; index < Text_dim; ++index ){
;
	lda     #$00
	sta     _index
	tax
L0120:	lda     _index
	cmp     _Text_dim
	txa
	sbc     #$00
	bcs     L0121
;
; PPU_DATA = 32; // clear the text by putting tile #32 in its place
;
	lda     #$20
	sta     $2007
;
; for ( index = 0; index < Text_dim; ++index ){
;
	inc     _index
	jmp     L0120
;
; PPU_ADDRESS = 0x21;
;
L0121:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xa8; // one line down = add 0x20 to the low bit
;
	lda     #$A8
	sta     $2006
;
; for ( index = 0; index < Text_dim; ++index ){
;
	lda     #$00
	sta     _index
L0122:	lda     _index
	cmp     _Text_dim
	txa
	sbc     #$00
	bcs     L0123
;
; PPU_DATA = 32; // clear the text by putting tile #32 in its place
;
	lda     #$20
	sta     $2007
;
; for ( index = 0; index < Text_dim; ++index ){
;
	inc     _index
	jmp     L0122
;
; PPU_ADDRESS = 0x21;
;
L0123:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xc8;
;
	lda     #$C8
	sta     $2006
;
; for ( index = 0; index < Text_dim; ++index ){
;
	lda     #$00
	sta     _index
L0124:	lda     _index
	cmp     _Text_dim
	txa
	sbc     #$00
	bcs     L0125
;
; PPU_DATA = 32; // clear the text by putting tile #32 in its place
;
	lda     #$20
	sta     $2007
;
; for ( index = 0; index < Text_dim; ++index ){
;
	inc     _index
	jmp     L0124
;
; PPU_ADDRESS = 0x21;
;
L0125:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xe8;
;
	lda     #$E8
	sta     $2006
;
; for ( index = 0; index < Text_dim; ++index ){
;
	lda     #$00
	sta     _index
L0126:	lda     _index
	cmp     _Text_dim
	txa
	sbc     #$00
	bcs     L0100
;
; PPU_DATA = 32; // clear the text by putting tile #32 in its place
;
	lda     #$20
	sta     $2007
;
; for ( index = 0; index < Text_dim; ++index ){
;
	inc     _index
	jmp     L0126
;
; }
;
L0100:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Change_Atrib_table (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Change_Atrib_table: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x23;
;
	lda     #$23
	sta     $2006
;
; PPU_ADDRESS = 0xda;
;
	lda     #$DA
	sta     $2006
;
; PPU_DATA =  Attrib_Table[nPalette];
;
	ldy     _nPalette
	lda     _Attrib_Table,y
	sta     $2007
;
; ++nPalette;
;
	inc     _nPalette
;
; if (nPalette>= sizeof(Attrib_Table))
;
	lda     _nPalette
	cmp     #$04
	bcc     L0117
;
; nPalette=0;
;
	lda     #$00
	sta     _nPalette
;
; }
;
L0117:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; All_Off();   // turn off screen
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; state=0;
;
	lda     #$00
	sta     _state
;
; test=0;
;
	sta     _test
;
; nPalette=0;
;
	sta     _nPalette
;
; All_On();// turn on screen
;
	jsr     _All_On
;
; while (NMI_flag == 0); // wait till NMI
;
L0127:	lda     _NMI_flag
	beq     L0127
;
; NMI_flag = 0;
;
	lda     #$00
	sta     _NMI_flag
;
; if (Frame_Count == 10){ // wait 30 frames = 0.5 seconds
;
	lda     _Frame_Count
	cmp     #$0A
	bne     L0127
;
; if (state == 0){
;
	lda     _state
	bne     L0076
;
; Load_Text();
;
	jsr     _Load_Text
;
; } else{
;
	jmp     L0079
;
; Change_Atrib_table();
;
L0076:	jsr     _Change_Atrib_table
;
; ++state;
;
	inc     _state
;
; ++test; // dummy, just making sure this compiles into the BSS section 0x300
;
L0079:	inc     _test
;
; if (  Text_Position == sizeof(TEXT) && state == 0)//& test>= 
;
	lda     _Text_Position
	cmp     #$11
	bne     L012A
	lda     _state
	bne     L012A
;
; state=1;
;
	lda     #$01
	sta     _state
;
; if (state>= 12){
;
L012A:	lda     _state
	cmp     #$0C
	bcc     L0084
;
; state=0;
;
	lda     #$00
	sta     _state
;
; nPalette=0;
;
	sta     _nPalette
;
; Change_Atrib_table();
;
	jsr     _Change_Atrib_table
;
; Reset_Scroll();
;
L0084:	jsr     _Reset_Scroll
;
; Frame_Count = 0;
;
	lda     #$00
	sta     _Frame_Count
;
; while (1){   // infinite loop
;
	jmp     L0127

.endproc

